name: npm CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v4
    - name: Set up node ${{ matrix.node-version }}
      uses: actions/setup-node
      with:
        python-version: ${{ matrix.nopde-version }}
    - name: Install Dependencies
      run: |
        cd frontend
        npm install
    # - name: Run Tests
    #   run: |
    #     python manage.py test
